yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path(
        'delete/<int:comment_id>/',
        views.comment_delete,
        name='comment_del'
    )
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_reset_form/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),) 

yatube/templates/includes/commentform.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card" style="width: 80vh; margin-left: 25vh;">
    <p class="card-header">Добавить комментарий:</p>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group">
          {{ form.text|addclass:'form-control' }}
        </div>
        <button type="submit" class="btn btn-info" style="margin-left: 3%; margin-bottom: 3vh;">Отправить</button>
      </form>
{% endif %}

yatube/templates/includes/comments.html
{% load static %}

{% for comment in comments %}
<div class="comment-post" style="margin-top: 2%;">
  <div class="card" style="width: 70vh; margin-top: -8px;">
    <div class="card-body" style="height: auto; min-height: 20px; margin-left: 0;">
      <h5>
        <a href="{% url 'posts:profile' comment.author.username %}">
          @{{ comment.author.username }}
        </a>
        {% if comment.author == request.user %}
        <div class="comment-del">
          <a href="{% url 'posts:comment_del' comment.id %}">
            <img src="{% static 'img/png/comment-del.ico' %}" width="15" height="15">
          </a>
        </div>
        {% endif%}
      </h5>
      <div class="comment-date">
        <small style="margin-left: 2%; margin-top: -3px;">
          {{comment.created|date:"d E Y"}}
        </small>
      </div>
      <p>
        {{ comment.text|linebreaksbr }}
      </p>
    </div>
  </div>
</div>
{% endfor %}
</div>
</div>

yatube/templates/includes/footer.html
<!--Footer-->
  <footer class="border-top text-center py-3">
    <p class="m-0 text-dark text-center ">
    <a href="{% url 'about:author' %}">Об авторе</a> |
    <a href="{% url 'about:tech' %}">Технологии</a>
    </p>
    <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
  </footer>

yatube/templates/includes/formerrors.html
{% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}            
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
{% endif %}

yatube/templates/includes/formfields.html
{% load user_filters %}
{% with request.resolver_match.view_name as view_name %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

  {% for field in form %}
    <div class="form-group"
      {% if field.field.required %}
        aria-required="true"
      {% else %}
        aria-required="false"
      {% endif %}
    >
      <label for="{{ field.id_for_label }}">
        {{ field.label }}
          {% if field.field.required %}
            <span class="required text-danger">*</span>
          {% endif %}
      </label>
      <div style='margin-left: 3%'>
      {{ field }}
        {% if field.help_text %}
          <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
            {{ field.help_text|safe }}
          </small>
        {% endif %}
      </div>
    </div>
  {% endfor %}
  <div class="col-md-6">
    <button type="submit" class="btn btn-info" href="{% url 'posts:index' %}">
      {% if view_name == 'users:login'%}
      Войти
      {% else %}
      Отправить
      {% endif %}
    </button>
  </div>
  </form>

{% endwith %}

yatube/templates/includes/header.html
{% with request.resolver_match.view_name as view_name %}
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

<!-- Navigation -->
<div class="fixed-top">
  <nav class="navbar navbar-expand-lg navbar-dark mx-background-top-linear">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}" style="text-transform: uppercase; font-size: 1.6em; "><span style="color:red; font-weight: bold;">Ya</span>tube</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li class="nav-item"> 
          <a class="nav-link" href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link" href="{% url 'users:password_reset_form' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link" href="{% url 'posts:profile' user %}">|  Пользователь: <span style="font-weight: bold;">{{ user }}</span></a>
        </li>
         {% else %}
         <li class="nav-item"> 
          <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</div>

{%endwith%}

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/includes/postcard.html
{% load thumbnail %}
{% load static %}
{% with request.resolver_match.view_name as view_name %}


<div class="card">
  {% if post.image %}
  <div class="card-header">
    {% if view_name == 'posts:post_detail' %}
    {% thumbnail post.image "900x450" padding=True as im %}
    <img src="{{ im.url }}" width="{{ im.width }}" alt="rover" />
    {% endthumbnail %}
    {% else %}
    {% thumbnail post.image "900x339" crop="top" upscale=True as im %}
    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="rover" />
    {% endthumbnail %}
    {% endif %}
  </div>
  {% endif %}
  <div class="card-body" style="margin: 2%;">
    {% if post.author == request.user %}
    <div class="pen">
      <a href="{% url 'posts:post_edit' post.id %}">
        <img src="{% static 'img/png/pen2.png' %}" width="20" height="20">
      </a>
    </div>
    {% endif %}
    {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">
      <span class="tag tag-tagle">{{ post.group.title }}</span>
    </a>
    {%endif%}
    {%if post.title %}
    <h4>{{ post.title }}</h4>
    {% else %}
    <h4>{{ post.text|truncatechars:30 }}</h4>
    {% endif %}
    {% if view_name == 'posts:post_detail' or post.text|length < 295 %}
    <p>{{ post.text|linebreaksbr }}</p>
    {% else %}
    <p>{{ post.text|linebreaksbr|truncatechars:295 }}
      <a href="{% url 'posts:post_detail' post.id %}">читать далее</a>
    </p>
    {% endif %}
    <div class="user">
      <div class="user-info">
        <a href="{% url 'posts:profile' post.author %}">
          <h5>@{{ post.author }}</h5>
        </a>
        <small>{{ post.created| date:"d E Y" }}</small>
      </div>
    </div>
    <div class="comment">
      <a href="{% url 'posts:post_detail' post.id %}">
        <img src="{% static 'img/png/comment.ico' %}" width="20" height="20" style="color: #00000">
          {{post.comments.count}}
      </a>
    </div>
  </div>
</div>
{% endwith %}

yatube/templates/includes/postcardprofile.html
{% load thumbnail %}
{% load static %}
{% with request.resolver_match.view_name as view_name %}

    <div class="card" style="width: 70%; margin-left: 30%;">
      {% if post.image %}
      <div class="card-header">
        {% thumbnail post.image "900x339" crop="top" upscale=True as im %}
        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="rover" />
        {% endthumbnail %}
      </div>
      {% endif %}
      <div class="card-body" style="margin: 2%;">
        {% if post.author == request.user %}
        <div class="pen">
          <a href="{% url 'posts:post_edit' post.id %}">
            <img src="{% static 'img/png/pen2.png' %}" width="20" height="20">
          </a>
        </div>
        {% endif %}
        {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">
          <span class="tag tag-tagle">{{ post.group.title }}</span>
        </a>
        {%endif%}
        {%if post.title %}
        <h4>{{ post.title }}</h4>
        {% else %}
        <h4>
            {{ post.text|truncatechars:30 }}
        </h4>
        {% endif %}
        {% if view_name == 'posts:post_detail' or post.text|length < 295 %}
          <p>
            {{ post.text|linebreaksbr }}
          </p>
        {% else %}
          <p>
            {{ post.text|linebreaksbr|truncatechars:295 }}
            <a href="{% url 'posts:post_detail' post.id %}">читать далее</a>
          </p>
        {% endif %}
          <div class="user">
            <div class="user-info">
              <a href="{% url 'posts:profile' post.author %}">
                <h5>@{{ post.author }}</h5>
              </a>
              <small>{{ post.created| date:"d E Y" }}</small>
            </div>
          </div>
          <div class="comment">
            <a href="{% url 'posts:post_detail' post.id %}">
              <img src="{% static 'img/png/comment.ico' %}" width="20" height="20" style="color: #00000">
              {{post.comments.count}}
            </a>
          </div>
        </div>
    </div>
{% endwith %}

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if follow %}disabled{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Подписки
        </a>
      </li>
    </ul>
  </div>
{% endif %}