yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path(
        'delete/<int:comment_id>/',
        views.comment_delete,
        name='comment_del'
    )
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),) 

yatube/posts/models.py
from core.models import CreatedModel
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название группы',
        help_text='Не больше 200 знаков'
    )
    slug = models.SlugField(
        max_length=100,
        unique=True,
        verbose_name='Имя ссылки',
        help_text=(
            'Введите название ссылки на стр. после "/"\n'
            'Не больше 100 знаков'
        )
    )
    description = models.TextField(
        max_length=1000,
        verbose_name='Описание группы',
        help_text='Не больше 1000 знаков'
    )

    def __str__(self) -> str:
        return self.title


class Post(CreatedModel):
    title = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        verbose_name='Заголовок поста',
        help_text='Не больше 50 знаков'
    )
    text = models.TextField(
        max_length=3000,
        verbose_name='Текст поста',
        help_text='Не больше 3000 знаков'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор поста',
        help_text='Выберите автора'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Сообщество',
        help_text='Выберите группу для поста'
    )

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-created',)
        default_related_name = 'posts'

    def __str__(self):
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='Комментарий',
        help_text='Напишите свое мнение',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор комментария',
    )
    text = models.TextField(
        max_length=500,
        verbose_name='Текст комментария',
        help_text='Не больше 500 знаков'
    )

    class Meta:
        ordering = ('-created',)
        default_related_name = 'comments'


class Follow(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['author', 'user'],
                name='unique_author_user'
            ),
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text', 'group', 'image',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User
from .utils import paginate_page


@cache_page(20, key_prefix='index_page')
def index(request):
    page_obj = paginate_page(
        request,
        Post.objects
        .select_related('group', 'author',)
        .prefetch_related('comments')
    )
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    page_obj = paginate_page(
        request,
        group.posts
        .select_related('group', 'author')
        .prefetch_related('comments')
    )
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('group').prefetch_related('comments')
    page_obj = paginate_page(request, posts)
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            author_id=author.id,
            user_id=request.user.id
        ).exists()
    else:
        following = None
    context = {
        'page_obj': page_obj,
        'author': author,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, id=post_id)
    comments = Comment.objects.filter(post=post)
    posts = post.author.posts.all()
    context = {
        'posts': posts,
        'post': post,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author)
    context = {
        'form': form,
        'is_edit': None,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = (
        Post.objects
        .select_related('author', 'group')
        .filter(author__following__user=request.user)
        .prefetch_related('comments')
    )
    page_obj = paginate_page(request, posts)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:follow_index')


@login_required
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.user == comment.author:
        Comment.objects.filter(id=comment.id).delete()
    return redirect('posts:post_detail', post_id=comment.post.id)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% load user_filters %}

{% block title %}
  {% if is_edit %} Добавление поста
  {% else %} Новый пост
  {% endif %}
{% endblock %}

{% block content %}
            <div class="card" style="width: 70vh; margin-left: 35vh;">
              <div class="card-header" style="margin-left: 0; margin-top: 0%; background-color: #70cee6;">       
                <h5>{% if is_edit %} Редактирование поста
                {% else %} Новый пост
                {% endif %}  
                </h5>
              </div>
              <div class="card-body">
              {% include 'includes/formerrors.html'%}
              {% include 'includes/formfields.html'%}
                        </div> <!-- card body -->
                      </div> <!-- card -->
                {% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load cache %}
{% load thumbnail %}

{% block title %} Лента подписок {% endblock %}

{% block content %}
        <h1> Лента подписок </h1>
        {% include 'includes/switcher.html' %}
        {% if page_obj|length > 0 %}
        {% for post in page_obj %}
          {% include 'includes/postcard.html'%}
        {% endfor %}
        {% include 'includes/paginator.html' %}
        {%else%}
        Пока что вы ни на кого не подписались:(
        {% endif %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %} Записи сообщества {{ group.title }} {% endblock %}

{% block content %}
        <h1> {{ group.title }} </h1>
        <p> {{ group.description }} </p>
        {% for post in page_obj %}
        {% include 'includes/postcard.html'%}
        {% endfor %}
      {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load cache %}
{% load thumbnail %}
{% load static %}

{% block title %} Последние обновления на сайте {% endblock %}

{% block content %}
        <h1> Последние обновления на сайте </h1>
        {% include 'includes/switcher.html' %}
        {% for post in page_obj %}
        <div class="container">
        {% include 'includes/postcard.html'%}
        </div>
        {% endfor %}
        {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}

{% load thumbnail %}

{% block title %} {{ post.text|truncatechars:30 }} {% endblock %}

{% block content %}
    {% include 'includes/postcard.html'%}
    {% include 'includes/commentform.html'%}
    {% include 'includes/comments.html'%}
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %} Профайл пользователя {{ author }} {% endblock %}

{% block content %}

<h1>Профиль пользователя {{ author }} </h1>
  <div class="card col-3" style="width: 20%; float: left; height: auto;">
    <div class="card-header" style="text-align: center; margin: 0;">
      <h5>{{ author.get_full_name }}</h5>
    </div>
    <div class="card-body" style="margin-left: -5vh;">
      <div>
      <ul>
        <li style="border-bottom: 1px solid #b3b3b3;">
          Всего постов: {{ page_obj.paginator.count }}
        </li>
        <li style="border-bottom: 1px solid #b3b3b3;">
          Подписчики: {{ author.following.count }}
        </li>
        <li style="border-bottom: 1px solid #b3b3b3;">
          Подписки: {{ author.follower.count }}
        </li>
        <li style="border-bottom: 1px solid #b3b3b3;">
          Комментарии: {{ author.comments.count }}
        </li>
        <li style="border-bottom: 1px solid #b3b3b3; margin-bottom: 2%;">
          Дата регистрации: <p>{{ author.date_joined| date:"d E Y"  }}</p>
        </li>
        <li style="margin-top: 20px;">
          {% if request.user.username == author.username %}
          <p>Ваш профиль</p>
          {% elif following == True %}
        <a class="btn btn-lg btn-secondary"
          href="{% url 'posts:profile_unfollow' author %}" role="button">
          Отписаться
        </a>
        {% else %}
        <a
          class="btn btn-lg btn-info"
          href="{% url 'posts:profile_follow' author %}" role="button">
          Подписаться
        </a>
        {% endif %}
        </li>
      </ul>
    </div>
    </div>
  </div>
        {% for post in page_obj %}
        {% include 'includes/postcardprofile.html'%}
        {% endfor %}
        {% include 'includes/paginator.html' %}
{% endblock %}